# Generated by Django 4.1.3 on 2022-11-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.IntegerField()),
                ('category_product', models.CharField(max_length=256)),
                ('sku_product', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('value_billing', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
